### ISSUE TITLE
Yunzai-Bot的py-plugin配合本插件使用报错

### ISSUE THREAD

**Issue by Georgebillion** [Mai-icy/nonebot-plugin-bread-shop#15]

**Comment by Georgebillion** [comment]
[YzBot][12:29:57.666][INFO] recv from: [Group: 惊！征婚小树与提瓦特(813319862), Member: GBKotori/Bot的主人 142967086(402520246)] #买面包
[YzBot][12:29:57.680][MARK] [群聊闭嘴][determine][惊！征婚小树与提瓦特(GBKotori/Bot的主人 142967086)] #买面包
[YzBot][12:29:57.680][MARK] [猜角色][guessAvatarCheck][惊！征婚小树与提瓦特(GBKotori/Bot的主人 142967086)] #买面包
[PyBot][04:29:57.673][INFO] [message]消息匹配成功: Matcher(type='message', module=nonebot_plugin_bread_shop)
[PyBot][04:29:57.673][SUCCESS] [message][message.group.normal] (群聊:813319862 用户:402520246)"#买面包"
[PyBot][04:29:57.674][ERROR] [message]Running Matcher(type='message', module=nonebot_plugin_bread_shop) failed.
Traceback (most recent call last):
  File "E:\蒙德同好会专用BOT\V3\Yunzai-Bot\plugins\py-plugin\main.py", line 13, in <module>
    nonebot.run(root)
  File "E:\蒙德同好会专用BOT\V3\Yunzai-Bot\plugins\py-plugin\nonebot\__init__.py", line 48, in run
    _driver.run()
  File "E:\蒙德同好会专用BOT\V3\Yunzai-Bot\plugins\py-plugin\nonebot\drivers.py", line 62, in run
    loop.run_until_complete(self.serve())
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\蒙德同好会专用BOT\V3\Yunzai-Bot\plugins\py-plugin\nonebot\message.py", line 130, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "E:\蒙德同好会专用BOT\V3\Yunzai-Bot\plugins\py-plugin\nonebot\message.py", line 182, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "E:\蒙德同好会专用BOT\V3\Yunzai-Bot\plugins\py-plugin\nonebot\internal\matcher.py", line 723, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "E:\蒙德同好会专用BOT\V3\Yunzai-Bot\plugins\py-plugin\nonebot\internal\matcher.py", line 698, in simple_run
    await handler(
  File "E:\蒙德同好会专用BOT\V3\Yunzai-Bot\plugins\py-plugin\nonebot\dependencies\__init__.py", line 83, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator.Bili-2021YGXTDT\AppData\Local\pypoetry\Cache\virtualenvs\py-plugin-2AoOCOoB-py3.10\lib\site-packages\nonebot_plugin_bread_shop\__init__.py", line 92, in _
    user_qq, group_id, name, msg_at, thing = await pre_get_data(event, bot, cmd, cmd_buy_ori)
  File "C:\Users\Administrator.Bili-2021YGXTDT\AppData\Local\pypoetry\Cache\virtualenvs\py-plugin-2AoOCOoB-py3.10\lib\site-packages\nonebot_plugin_bread_shop\__init__.py", line 485, in pre_get_data
    name = await get_nickname(bot, user_qq, group_id)
  File "C:\Users\Administrator.Bili-2021YGXTDT\AppData\Local\pypoetry\Cache\virtualenvs\py-plugin-2AoOCOoB-py3.10\lib\site-packages\nonebot_plugin_bread_shop\__init__.py", line 461, in get_nickname
    other_name = info.get("nickname", "")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by Mai-icy** [comment]
报错在获取用户名的地方，请问是否已更新到最新版本
（我好久没有上传pypi了）

**Comment by Georgebillion** [comment]
emmm,手动更新吗？

**Comment by Georgebillion** [comment]
用的还是pypi、安装的

**Comment by Mai-icy** [comment]
先手动更新一下试试，我等下上传pypi

**Comment by Georgebillion** [comment]
[YzBot][12:39:36.068][INFO] recv from: [Group: 惊！征婚小树与提瓦特(813319862), Member: GBKotori/Bot的主人 142967086(402520246)] #买面包
[PyBot][04:39:36.075][INFO] [message]消息匹配成功: Matcher(type='message', module=nonebot_plugin_bread_shop)
[PyBot][04:39:36.075][SUCCESS] [message][message.group.normal] (群聊:813319862 用户:402520246)"#买面包"
[PyBot][04:39:36.076][ERROR] [message]Running Matcher(type='message', module=nonebot_plugin_bread_shop) failed.
Traceback (most recent call last):
  File "E:\蒙德同好会专用BOT\V3\Yunzai-Bot\plugins\py-plugin\main.py", line 13, in <module>
    nonebot.run(root)
  File "E:\蒙德同好会专用BOT\V3\Yunzai-Bot\plugins\py-plugin\nonebot\__init__.py", line 48, in run
    _driver.run()
  File "E:\蒙德同好会专用BOT\V3\Yunzai-Bot\plugins\py-plugin\nonebot\drivers.py", line 62, in run
    loop.run_until_complete(self.serve())
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\蒙德同好会专用BOT\V3\Yunzai-Bot\plugins\py-plugin\nonebot\message.py", line 130, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "E:\蒙德同好会专用BOT\V3\Yunzai-Bot\plugins\py-plugin\nonebot\message.py", line 182, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "E:\蒙德同好会专用BOT\V3\Yunzai-Bot\plugins\py-plugin\nonebot\internal\matcher.py", line 723, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "E:\蒙德同好会专用BOT\V3\Yunzai-Bot\plugins\py-plugin\nonebot\internal\matcher.py", line 698, in simple_run
    await handler(
  File "E:\蒙德同好会专用BOT\V3\Yunzai-Bot\plugins\py-plugin\nonebot\dependencies\__init__.py", line 83, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator.Bili-2021YGXTDT\AppData\Local\pypoetry\Cache\virtualenvs\py-plugin-2AoOCOoB-py3.10\lib\site-packages\nonebot_plugin_bread_shop\__init__.py", line 92, in _
    user_qq, group_id, name, msg_at, thing = await pre_get_data(event, bot, cmd, cmd_buy_ori)
  File "C:\Users\Administrator.Bili-2021YGXTDT\AppData\Local\pypoetry\Cache\virtualenvs\py-plugin-2AoOCOoB-py3.10\lib\site-packages\nonebot_plugin_bread_shop\__init__.py", line 485, in pre_get_data
    name = await get_nickname(bot, user_qq, group_id)
  File "C:\Users\Administrator.Bili-2021YGXTDT\AppData\Local\pypoetry\Cache\virtualenvs\py-plugin-2AoOCOoB-py3.10\lib\site-packages\nonebot_plugin_bread_shop\__init__.py", line 461, in get_nickname
    other_name = info.get("nickname", "")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by Georgebillion** [comment]
还是无效，手动更新之后还是这样

**Comment by Mai-icy** [comment]
报错出在获取用户名，稍等，正在排查

**Comment by Mai-icy** [comment]
请发一下您的`nonebot2`版本以及`nonebot-adapter-onebot`版本

**Comment by Georgebillion** [comment]
![image](https://user-images.githubusercontent.com/40432824/202970741-9486638b-f358-4917-8c94-d93a0f1dd43e.png)

**Comment by Georgebillion** [comment]
nb2是最新版本的RC1了

**Comment by Mai-icy** [comment]
暂时有事，晚些时候查看
（我升级到同版本也是正常的）

**Comment by Mai-icy** [comment]
日志体现貌似是您的`bot.get_stranger_info()`函数返回了`None`
查阅文档没有说明这样的情况
我难以复现，一切正常。
可能因为您使用了某个bot框架导致（可能）
我已将我的测试bot拉入您的群聊可尝试输入`/buy`以便我尝试复现问题

**Comment by Mai-icy** [comment]
总结后为`Yunzai-Bot`的`py-plugin`插件不完善，请关注`py-plugin`作者更新，本插件不会修改。

**Comment by Mai-icy** [comment]
其作者已更新插件
