### ISSUE TITLE
无法响应@参数

### ISSUE THREAD

**Issue by ABKQPO** [Mai-icy/nonebot-plugin-bread-shop#18]
01-10 16:05:40 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_bread_shop, lineno=68) failed.
Traceback (most recent call last):
  File "<string>", line 19, in <module>
  File "D:\NoneBot\nb\.venv\lib\site-packages\nonebot\__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "D:\NoneBot\nb\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 189, in run
    uvicorn.run(
  File "D:\NoneBot\nb\.venv\lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "D:\NoneBot\nb\.venv\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\NoneBot\nb\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "D:\NoneBot\nb\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\NoneBot\nb\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 846, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\NoneBot\nb\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 821, in simple_run
    await handler(
  File "D:\NoneBot\nb\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\NoneBot\nb\.venv\lib\site-packages\nonebot_plugin_bread_shop\__init__.py", line 188, in _
    event_.set_other_id(robbed_qq, robbed_name)
  File "D:\NoneBot\nb\.venv\lib\site-packages\nonebot_plugin_bread_shop\bread_operate.py", line 142, in set_other_id
    self.other_data = self.bread_db.get_bread_data(other_id)
  File "D:\NoneBot\nb\.venv\lib\site-packages\nonebot_plugin_bread_shop\bread_handle.py", line 47, in wrapper
    raise TypeError('Argument {} must be {}'.format(name, str))
TypeError: Argument user_id must be <class 'str'>

**Comment by Mai-icy** [comment]
请问使用的平台以及接口
有没有修改过某些配置项🤔️
