### ISSUE TITLE
pydantic库版本更新以及无法适配satori协议

### ISSUE THREAD

**Issue by XibieTime** [Mai-icy/nonebot-plugin-bread-shop#19]
bot启动时出现如下报错，求更新修复

04-24 19:32:14 [ERROR] nonebot | Failed to import "nonebot_plugin_bread_shop"
Traceback (most recent call last):
  File "<string>", line 18, in <module>
  File "C:\Users\Maniera\Documents\AINonebot\WST\T\.venv\lib\site-packages\nonebot\plugin\load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Maniera\Documents\AINonebot\WST\T\.venv\lib\site-packages\nonebot\plugin\load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Maniera\Documents\AINonebot\WST\T\.venv\lib\site-packages\nonebot\plugin\manager.py", line 176, in load_all_plugins
    return set(
  File "C:\Users\Maniera\Documents\AINonebot\WST\T\.venv\lib\site-packages\nonebot\plugin\manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Maniera\Documents\AINonebot\WST\T\.venv\lib\site-packages\nonebot\plugin\manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Maniera\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Maniera\Documents\AINonebot\WST\T\.venv\lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Maniera\Documents\AINonebot\WST\T\.venv\lib\site-packages\nonebot_plugin_bread_shop\__init__.py", line 13, in <module>
    from .bread_handle import BreadDataManage, Action
  File "C:\Users\Maniera\Documents\AINonebot\WST\T\.venv\lib\site-packages\nonebot_plugin_bread_shop\bread_handle.py", line 13, in <module>
    from .config import LEVEL
  File "C:\Users\Maniera\Documents\AINonebot\WST\T\.venv\lib\site-packages\nonebot_plugin_bread_shop\config.py", line 5, in <module>
    from pydantic import BaseSettings, Extra
  File "C:\Users\Maniera\Documents\AINonebot\WST\T\.venv\lib\site-packages\pydantic\__init__.py", line 380, in __getattr__
    return _getattr_migration(attr_name)
  File "C:\Users\Maniera\Documents\AINonebot\WST\T\.venv\lib\site-packages\pydantic\_migration.py", line 296, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.7/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.7/u/import-error

**Comment by Mai-icy** [comment]
`pydantic`的版本升级到了v2，确认安装`pydantic-settings`第三方库
改为 `from pydantic_settings import BaseSettings`

**Comment by XibieTime** [comment]
> `pydantic`的版本升级到了v2，确认安装`pydantic-settings`第三方库 改为 `from pydantic_settings import BaseSettings`

我先在bot文件夹下pip install pydantic-settings，然后把config.py内的from pydantic import BaseSettings, Extra改为了from pydantic_settings import BaseSettings, Extra。启动bot时报错ModuleNotFoundError: No module named 'pydantic_settings'。；；我该在哪里安装pydantic-settings第三方库？

**Comment by Mai-icy** [comment]
如果你的bot使用的是venv虚拟环境请在venv的Scripts文件夹下pip，否则请在对应使用的版本的python的文件夹Scripts下pip。如果您是通过pip下载本插件的，就相同状态安装这个库。
```python
from pydantic_settings import BaseSettings
from pydantic import Extra
```

**Comment by XibieTime** [comment]
感谢耐心解答，插件已正常运行。

**Comment by XibieTime** [comment]
插件正常加载，然而bot对任何指令都没有反应，日志如下
04-24 22:49:28 [SUCCESS] nonebot | Satori 2141373602 | [message-created]: Message 7361445824315856877 from 一念无量劫(718055270)@[测试:718055270]: [Text(type='text', data={'text': '买面包', 'styles': {}})]
04-24 22:49:28 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_bread_shop, lineno=66)
04-24 22:49:28 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_bread_shop, lineno=66) running complete
04-24 22:49:32 [SUCCESS] nonebot | Satori 2141373602 | [message-created]: Message 7361445839782655180 from 一念无量劫(718055270)@[测试:718055270]: [Text(type='text', data={'text': '吃面包', 'styles': {}})]
04-24 22:49:32 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_bread_shop, lineno=67)
04-24 22:49:32 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_bread_shop, lineno=67) running complete
04-24 22:49:32 [SUCCESS] nonebot | Satori 2141373602 | [message-created]: Message 7435662874684912712 from T.(718055270)@[测试:718055270]: [Text(type='text', data={'text': '输入文字数量不符，文字数量应为 0，但当前为 1。', 'styles': {}})]
04-24 22:49:36 [SUCCESS] nonebot | Satori 2141373602 | [message-created]: Message 7361445858584335656 from 一念无量劫(718055270)@[测试:718055270]: [Text(type='text', data={'text': '送面包', 'styles': {}})]
04-24 22:49:36 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_bread_shop, lineno=69)
04-24 22:49:36 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_bread_shop, lineno=69) running complete
04-24 22:49:42 [SUCCESS] nonebot | Satori 2141373602 | [message-created]: Message 7361445884269372451 from 一念无量劫(718055270)@[测试:718055270]: [Text(type='text', data={'text': '抢面包', 'styles': {}})]
04-24 22:49:42 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_bread_shop, lineno=68)
04-24 22:49:42 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_bread_shop, lineno=68) running complete
![image](https://github.com/Mai-icy/nonebot-plugin-bread-shop/assets/139568737/24eff657-bc69-4000-81bf-914755495692)
![image](https://github.com/Mai-icy/nonebot-plugin-bread-shop/assets/139568737/aab12abc-b281-489c-a28b-6005808bbbd2)
![image](https://github.com/Mai-icy/nonebot-plugin-bread-shop/assets/139568737/70fbfd5d-4e39-42ae-9ccb-d218ea76f970)
其中 ”输入文字数量不符，文字数量应为 0，但当前为 1“应该是响应了表情包制作插件中的指令 吃
适配器为Satori协议的Chronocat
其他插件的指令可正常响应

**Comment by Mai-icy** [comment]
请问是使用了[NoneBot-Adapter-Satori](https://github.com/nonebot/adapter-satori)吗？

**Comment by Mai-icy** [comment]
本项目完成于两年前，并没有和其他插件的适配。
如果使用的是这个，在其[README](https://github.com/nonebot/adapter-satori/blob/main/README.md)中有写
```python
from nonebot.adapters.satori import Bot
from nonebot.adapters.satori.event import MessageEvent
from nonebot.adapters.satori.message import MessageSegment
```
所以请将本项目`__init__.py`文件中对adapters的使用进行修改
```python
from nonebot import get_driver
from nonebot import on_command
from nonebot.params import CommandArg, RawCommand
from nonebot.adapters.onebot.v11 import Bot, Event, Message
from nonebot.exception import ActionFailed
```
我预测修改为
```python
from nonebot import get_driver
from nonebot import on_command
from nonebot.params import CommandArg, RawCommand
from nonebot.exception import ActionFailed

from nonebot.adapters.satori import Bot
from nonebot.adapters.satori.event import Event
from nonebot.adapters.satori.message import Message
```

**Comment by XibieTime** [comment]
使用的确实是[NoneBot-Adapter-Satori](https://github.com/nonebot/adapter-satori)。根据您的指点改动_init_.py后，bot成功加载，然而在发送指令时出现如下报错：
04-25 14:05:01 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_bread_shop, lineno=70) failed.
Traceback (most recent call last):
  File "<string>", line 21, in <module>
  File "C:\Users\Maniera\Documents\AINonebot\WST\T\.venv\lib\site-packages\nonebot\__init__.py", line 334, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Maniera\Documents\AINonebot\WST\T\.venv\lib\site-packages\nonebot\drivers\none.py", line 56, in run
    loop.run_until_complete(self._serve())
  File "C:\Users\Maniera\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Maniera\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Maniera\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Maniera\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Maniera\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Maniera\Documents\AINonebot\WST\T\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\Maniera\Documents\AINonebot\WST\T\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Maniera\Documents\AINonebot\WST\T\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 842, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Maniera\Documents\AINonebot\WST\T\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 817, in simple_run
    await handler(
  File "C:\Users\Maniera\Documents\AINonebot\WST\T\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 106, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Maniera\Documents\AINonebot\WST\T\.venv\lib\site-packages\nonebot_plugin_bread_shop\__init__.py", line 122, in _
    user_qq, group_id, name, msg_at, thing = await pre_get_data(event, bot, cmd, cmd_eat_ori)
  File "C:\Users\Maniera\Documents\AINonebot\WST\T\.venv\lib\site-packages\nonebot_plugin_bread_shop\__init__.py", line 491, in pre_get_data
    group_id = await get_group_id(event.get_session_id())
  File "C:\Users\Maniera\Documents\AINonebot\WST\T\.venv\lib\site-packages\nonebot_plugin_bread_shop\__init__.py", line 421, in get_group_id
    group_id = res[0]
IndexError: list index out of range

现已经换回之前的onebot协议并成功使用了。非常好插件群友特别喜欢玩，已经玩了一年了每天都在玩，如果有条件的话能更新就再好不过了TAT

**Comment by Mai-icy** [comment]
具体原因应该是插件不适配导致的，我已经很久没有维护这个代码了，也没有环境运行和调试。
应该是`event.get_session_id()`函数返回，在satori协议和onebot协议的不同返回情况导致的。
如果有条件和能力可以进行自行微调`__init__.py`的 get_group_id 函数，以适配satori协议

**Comment by Mai-icy** [comment]
盲猜一手，在satori协议的`event.get_session_id()`返回的是直接的群号，可以尝试修改`__init__.py` : 407

```python
async def get_group_id(session_id):
    res = re.findall("_(.*)_", session_id)
    group_id = res[0]

    # 调整是否全局分群
    for zone_pair in bread_config.group_database.items():
        if group_id in zone_pair[1]:
            return zone_pair[0]

    if bread_config.global_database:
        return "global"
    else:
        return group_id
```
改为
```python
async def get_group_id(session_id):
    group_id = session_id

    # 调整是否全局分群
    for zone_pair in bread_config.group_database.items():
        if group_id in zone_pair[1]:
            return zone_pair[0]

    if bread_config.global_database:
        return "global"
    else:
        return group_id
```

估计可以解决

**Comment by XibieTime** [comment]
> 盲猜一手，在satori协议的`event.get_session_id()`返回的是直接的群号，可以尝试修改`__init__.py` : 407
> 
> ```python
> async def get_group_id(session_id):
>     res = re.findall("_(.*)_", session_id)
>     group_id = res[0]
> 
>     # 调整是否全局分群
>     for zone_pair in bread_config.group_database.items():
>         if group_id in zone_pair[1]:
>             return zone_pair[0]
> 
>     if bread_config.global_database:
>         return "global"
>     else:
>         return group_id
> ```
> 
> 改为
> 
> ```python
> async def get_group_id(session_id):
>     group_id = session_id
> 
>     # 调整是否全局分群
>     for zone_pair in bread_config.group_database.items():
>         if group_id in zone_pair[1]:
>             return zone_pair[0]
> 
>     if bread_config.global_database:
>         return "global"
>     else:
>         return group_id
> ```
> 
> 估计可以解决

如此修改后，使用指令时出现如下报错
 
![image](https://github.com/Mai-icy/nonebot-plugin-bread-shop/assets/139568737/c157142f-91c1-473a-9160-05319f8a139f)

**Comment by XibieTime** [comment]
> 具体原因应该是插件不适配导致的，我已经很久没有维护这个代码了，也没有环境运行和调试。 应该是`event.get_session_id()`函数返回，在satori协议和onebot协议的不同返回情况导致的。 如果有条件和能力可以进行自行微调`__init__.py`的 get_group_id 函数，以适配satori协议

目前已经用回onebot协议解决问题了，不方便的话就不麻烦了，用onebot也可以

**Comment by Mai-icy** [comment]
好的，感谢您的提出，本插件暂时不对适配进行更新了，如有能力，推荐提pr
